"""empty message

Revision ID: fd47f9434599
Revises: 
Create Date: 2022-04-24 18:21:02.660568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd47f9434599'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collaborator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=40), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('dependents', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collaborator')
    op.drop_table('department')
    # ### end Alembic commands ###
